# Generated by Django 5.1.7 on 2025-03-23 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 11, 10, 13, 994961)),
        ),
        migrations.AlterField(
            model_name='specifiche',
            name='ValSpecCli',
            field=models.CharField(choices=[('NC', 'NC'), ('OK', 'OK'), ('NO', 'NO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specifiche',
            name='ValSpecTec',
            field=models.CharField(choices=[('NC', 'NC'), ('OK', 'OK'), ('NO', 'NO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specificheurg',
            name='ValSpecCli',
            field=models.CharField(choices=[('NC', 'NC'), ('OK', 'OK'), ('NO', 'NO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specificheurg',
            name='ValSpecTec',
            field=models.CharField(choices=[('NC', 'NC'), ('OK', 'OK'), ('NO', 'NO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urgenterequest',
            name='ValSpecCli',
            field=models.CharField(choices=[('NC', 'NC'), ('OK', 'OK'), ('NO', 'NO')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urgenterequest',
            name='ValSpecTec',
            field=models.CharField(choices=[('NC', 'NC'), ('OK', 'OK'), ('NO', 'NO')], max_length=255, null=True),
        ),
    ]
