# Generated by Django 5.1.7 on 2025-03-24 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAG', '0003_alter_main_data_alter_specifiche_valspeccli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabbisogni',
            name='Data',
            field=models.DateTimeField(default='24/03/2025'),
        ),
        migrations.AlterField(
            model_name='main',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 9, 20, 0, 391723)),
        ),
        migrations.AlterField(
            model_name='specifiche',
            name='ValSpecCli',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specifiche',
            name='ValSpecTec',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specificheurg',
            name='ValSpecCli',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specificheurg',
            name='ValSpecTec',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urgenterequest',
            name='ValSpecCli',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urgenterequest',
            name='ValSpecTec',
            field=models.CharField(choices=[('OK', 'OK'), ('NO', 'NO'), ('NC', 'NC')], max_length=255, null=True),
        ),
    ]
