# Generated by Django 5.1.7 on 2025-03-27 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAG', '0004_alter_fabbisogni_data_alter_main_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabbisogni',
            name='Data',
            field=models.DateTimeField(default='27/03/2025'),
        ),
        migrations.AlterField(
            model_name='main',
            name='Data',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 10, 39, 38, 85954)),
        ),
        migrations.AlterField(
            model_name='specifiche',
            name='ValSpecCli',
            field=models.CharField(choices=[('NO', 'NO'), ('OK', 'OK'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specifiche',
            name='ValSpecTec',
            field=models.CharField(choices=[('NO', 'NO'), ('OK', 'OK'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specificheurg',
            name='ValSpecCli',
            field=models.CharField(choices=[('NO', 'NO'), ('OK', 'OK'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specificheurg',
            name='ValSpecTec',
            field=models.CharField(choices=[('NO', 'NO'), ('OK', 'OK'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urgenterequest',
            name='ValSpecCli',
            field=models.CharField(choices=[('NO', 'NO'), ('OK', 'OK'), ('NC', 'NC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urgenterequest',
            name='ValSpecTec',
            field=models.CharField(choices=[('NO', 'NO'), ('OK', 'OK'), ('NC', 'NC')], max_length=255, null=True),
        ),
    ]
